version: "3"
services:
  web:
    image: codebottle
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - webnet
    env_file:
      - .env
networks:
  webnet: