version: "3.4"
services:
  web:
    tty: true
    image: registry.gitlab.com/codebottle/codebottle
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - webnet
    env_file:
      - .env
networks:
  webnet: