version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Copy .env template
          command: cp ./.env.example ./.env
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Create nyc_output folder
          command: mkdir -p ./.nyc_output
      - run:
          name: Run tests
          command: npm run tests:coverage
      - run:
          name: Generate code coverage
          command: ./node_modules/.bin/nyc report > /tmp/test-results.txt
      - store_artifacts:
          path: /tmp/test-results.txt